import os
import sys

from github_utilities import comment_on_issue, get_conversation_on_issue, get_most_recent_comment_on_issue
from claude import prompt_claude

print("Hello")
# Read the environment variable "ANTHROPIC_API_KEY"
api_key = os.environ.get("ANTHROPIC_API_KEY")

# Check if the environment variable is not None
print("Hello")
if api_key is not None:
    print("world!")
if api_key[0] == '"':
    print("nej!")

# Print out all arguments passed to the script
print("Script arguments:")
for arg in sys.argv[1:]:
    print(arg)

task = sys.argv[1]
repository = sys.argv[2] if len(sys.argv) > 2 else None
issue = int(sys.argv[3]) if len(sys.argv) > 3 else None

if task == "response-pull-request":

    user, text = get_most_recent_comment_on_issue(repository, issue)
    remark = "<sup>This comment was generated by [git-bob](https://github.com/haesleinhuepf/git-bob), an AI-based assistant.</sup>"

    if "git-bob respond" in text and remark not in text:

        discussion = get_conversation_on_issue(repository, issue)

        print("Discussion:", discussion)

        # load temp.txt into a variable
        with open("temp.txt", "r") as file:
            file_changes = file.read()

        print("file_changes:", file_changes)

        comment = prompt_claude(f"""
You are a an extremely skilled python developer.
Generate a response to a github pull-request. 
Given are the discussion on the pull-request and the changed files.

## Discussion

{discussion}

## Change files

{file_changes}

## Your task

Respond to the discussion above. 
Do NOT explain your response or anything else. 
Just respond to the discussion.
""")

        print("comment:", comment)

        comment_on_issue(repository, issue, f"""        
{remark}
---
{comment}
""")

